---
title: "Dimerization Model: Simulation and Fitting"
author: "Ren-Huai Huang"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, echo = FALSE, results = FALSE, warning = FALSE, message = FALSE}
require(reshape2); require(ggplot2); require(grid)
knitr::opts_chunk$set(fig.height = 4, fig.width = 4)
```

## Simulation & plotting: 
```{r}

#  parameters for simulation
par = list(kon  = 2e2, koff = 1e-2, rmax = 1)
concs <- 1e-5 * (2^(0:5));
time = seq(0, 300, length.out = 1501); 
t2   = 150

# simulation
ySimulated <- yPred_df(par = par, concs = concs, time = time, t2 = t2, y_data = NULL) 

# Add errors to the simulated data
ySimulated <- ySimulated + rnorm(ncol(ySimulated)*nrow(ySimulated), sd = 0.01)

# plot the simulation
# with(ySimulated, plot(time, V6, type = "l")); for( i in 1:5) with(ySimulated, lines(time, ySimulated[[i]]))
# another way to plot
colnames(ySimulated) = concs
ySimulated$Time = time; 
dat <-reshape2::melt(data = ySimulated, id.vars = "Time", measure.vars = rev(1:6), variable.name = "Conc")

g <- ggplot() + theme_classic() 
g <- g + theme(legend.position=c(0.95, 0.65),
            legend.text=element_text(size = rel(1)),
            legend.key.size=unit(0.9,"line"));
g <- g + geom_line(data = dat, aes(x = Time, y = value, color = Conc));
g <- g + xlab("Time (sec)") + ylab("Response (nm)") + ylim(-0.025,1);
g <- g + labs(linetype= 'title')
print(g)
```

## Fitting & plotting: 
```{r}
# initilization for fitting. 
initPar_test = list(kon =1, koff = 1, rmax = 1) 
env_test <- new.env(parent = emptyenv())
env_test$t2 <- 149.9 # t2 is the beginning of the diassociation. 
env_test$lowerBound = list(kon =1e-04, koff=1e-04, rmax = 0.01);
env_test$upperBound = list(kon =1e04, koff=1e04, rmax = 10);
env_test$concs      = concs;
env_test$datF       = within(ySimulated, rm("Time")); 
env_test$Time       = time;

# Fit
# test residFun.
# resid_array <- residFun(par= par)

fit <- kinFit(par = initPar_test, env = env_test)
names(fit)
par # simulation parameters
fit$par # paramenters after fitting
cbind(simulation= par, init = initPar_test, fitting = fit$par)

#prodict and plot
predFit <- yPred_dft(par = fit$par, concs = concs, time = time, t2 = t2, y_data = NULL)
predFit <- reshape2::melt(predFit, id.vars = "Time")
g + geom_line(data=predFit, aes(x = Time, y = value, group = variable) ) 

```
