---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
%\VignetteIndexEntry{Vignette Title}
%\VignetteEngine{knitr::rmarkdown}
%\VignetteEncoding{UTF-8}
---

## Test with simulated data
```{r}
require(reshape2); 
require(ggplot2);
require(grid)
require(pldfit)
require(xyFit)
# simulate the data use the following parameters
par = list(kon  = 2e2, koff = 1e-2, rmax = 1)
concs <- 1e-5 * (2^(0:5));
time = seq(0, 300, length.out = 1501); 
t2   = 150

# simulation
ySimulated <- yPred_df(par = par, concs = concs, time = time, t2 = t2, y_data = NULL) 

# Add some error to the simulated data
ySimulated <- ySimulated + rnorm(ncol(ySimulated)*nrow(ySimulated), sd = 0.01)

# plot the simulation

# another way to plot
colnames(ySimulated) = concs
ySimulated$Time = time; 
dat <-reshape2::melt(data = ySimulated, 
                     id.vars = "Time", 
                     measure.vars = rev(1:6), 
                     variable.name = "Conc")

g <- ggplot() + theme_classic() + xlab("Time (sec)") + ylab("Response (nm)") +
    labs(linetype= 'title') + ylim(-0.025,1) + 
    theme(legend.position=c(0.95, 0.65),
          legend.text=element_text(size = rel(1)),
          legend.key.size=unit(0.9,"line"));
g <- g + geom_line(data = dat, aes(x = Time, y = value, color = Conc));
print(g)

```

## Fitting
```{r}

# init
initPar_test = list(kon =1, koff = 1, rmax = 1) 
env_test <- new.env(parent = emptyenv())
env_test$t2 <- 149.9 # t2 is the beginning of the diassociation. 
env_test$lowerBound = list(kon =1e-04, koff=1e-04, rmax = 0.01);
env_test$upperBound = list(kon =1e04, koff=1e04, rmax = 10);
env_test$concs      = concs;
env_test$datF       = within(ySimulated, rm("Time")); 
env_test$Time       = time;
# source("~/Documents/My_Exp/2012BLI_Sadler/model/Rmd/helper.R")
# test residFun.
resid_array <- residFun(par= par)

# Fit
fit <- kinFit(par = initPar_test, env = env_test)
names(fit)
par # simulation parameters
fit$par # paramenters after fitting
cbind(simulation= par, init = initPar_test, fitting = fit$par)

#prodict and plot
predFit <- yPred_dft(par = fit$par, concs = concs, time = time, t2 = t2, y_data = NULL)
predFit <- reshape2::melt(predFit, id.vars = "Time")
g + geom_line(data=predFit, aes(x = Time, y = value, group = variable) ) 

```
